name: Tests

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
        continue-on-error: true

      - name: Create Build Environment
        run: git submodule update --init --recursive

      - name: Create Build Environment
        run: |
          apt-get update
          apt-get install -y libhdf5-dev libboost-all-dev protobuf-compiler libprotobuf-dev cmake

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBACKPROP_TOOLS_RL_ENVIRONMENTS_ENABLE_MUJOCO:BOOL=ON -DBACKPROP_TOOLS_ENABLE_TENSORBOARD:BOOL=ON -DBACKPROP_TOOLS_ENABLE_HDF5:BOOL=ON -DBACKPROP_TOOLS_ENABLE_CLI11:BOOL=ON

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest
